# Templates module - Import from all_templates.py file
from .all_templates import (
    INVOICE_TEMPLATE, HEADER_TEMPLATE, LINE_ITEMS_TEMPLATE, FOOTER_TEMPLATE, CSS_CONTENT,
    REMINDER_TEMPLATE as PAYMENT_REMINDER_TEMPLATE
)

# Create REMINDER_CSS_CONTENT alias for backward compatibility
REMINDER_CSS_CONTENT = CSS_CONTENT

__all__ = [
    'INVOICE_TEMPLATE', 'HEADER_TEMPLATE', 'LINE_ITEMS_TEMPLATE', 'FOOTER_TEMPLATE', 'CSS_CONTENT',
    'PAYMENT_REMINDER_TEMPLATE', 'REMINDER_CSS_CONTENT'
]